import { Injectable } from '@angular/core';
import { ICountry } from '../models/Icountry';

@Injectable({
  providedIn: 'root'
})
export class CountryListService {

  constructor() { }

  // filter the list based on the user's input chars
  public filterCountries(value: string): ICountry[] {
    const filterValue = value.toLowerCase();

    return this.countries.filter(country => country.name.toLowerCase().includes(filterValue));
  }

  countries = [
    { code: '64', acr: 'nz', name: 'New Zealand (+64)', flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arkansas.svg' },
    { code: '61', acr: 'au', name: 'Australia (+61)', flag: 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_California.svg' },
    { code: '1', acr: 'us', name: 'USA (+1)', flag: '' },
    { code: '44', acr: 'gb', name: 'UK (+44)', flag: '' },
    { code: '213', acr: 'dz', name: 'Algeria (+213)', flag: '' },
    { code: '376', acr: 'ad', name: 'Andorra (+376)', flag: '' },
    { code: '244', acr: 'ao', name: 'Angola (+244)', flag: '' },
    { code: '1264', acr: 'ai', name: 'Anguilla (+1264)', flag: '' },
    { code: '1268', acr: 'ag', name: 'Antigua &amp; Barbuda (+1268)', flag: '' },
    { code: '54', acr: 'ar', name: 'Argentina (+54)', flag: '' },
    { code: '374', acr: 'am', name: 'Armenia (+374)', flag: '' },
    { code: '297', acr: 'aw', name: 'Aruba (+297)', flag: '' },
    { code: '43', acr: 'at', name: 'Austria (+43)', flag: '' },
    { code: '994', acr: 'az', name: 'Azerbaijan (+994)', flag: '' },
    { code: '1242', acr: 'bs', name: 'Bahamas (+1242)', flag: '' },
    { code: '973', acr: 'bh', name: 'Bahrain (+973)', flag: '' },
    { code: '880', acr: 'bd', name: 'Bangladesh (+880)', flag: '' },
    { code: '1246', acr: 'bb', name: 'Barbados (+1246)', flag: '' },
    { code: '375', acr: 'by', name: 'Belarus (+375)', flag: '' },
    { code: '32', acr: 'be', name: 'Belgium (+32)', flag: '' },
    { code: '501', acr: 'bz', name: 'Belize (+501)', flag: '' },
    { code: '229', acr: 'bj', name: 'Benin (+229)', flag: '' },
    { code: '1441', acr: 'bm', name: 'Bermuda (+1441)', flag: '' },
    { code: '975', acr: 'bt', name: 'Bhutan (+975)', flag: '' },
    { code: '591', acr: 'bo', name: 'Bolivia (+591)', flag: '' },
    { code: '387', acr: 'ba', name: 'Bosnia Herzegovina (+387)', flag: '' },
    { code: '267', acr: 'bw', name: 'Botswana (+267)', flag: '' },
    { code: '55', acr: 'br', name: 'Brazil (+55)', flag: '' },
    { code: '673', acr: 'bn', name: 'Brunei (+673)', flag: '' },
    { code: '359', acr: 'bg', name: 'Bulgaria (+359)', flag: '' },
    { code: '226', acr: 'bf', name: 'Burkina Faso (+226)', flag: '' },
    { code: '257', acr: 'bi', name: 'Burundi (+257)', flag: '' },
    { code: '855', acr: 'kh', name: 'Cambodia (+855)', flag: '' },
    { code: '237', acr: 'cm', name: 'Cameroon (+237)', flag: '' },
    { code: '1', acr: 'ca', name: 'Canada (+1)', flag: '' },
    { code: '238', acr: 'cv', name: 'Cape Verde Islands (+238)', flag: '' },
    { code: '1345', acr: 'ky', name: 'Cayman Islands (+1345)', flag: '' },
    { code: '236', acr: 'cf', name: 'Central African Republic (+236)', flag: '' },
    { code: '56', acr: 'cl', name: 'Chile (+56)', flag: '' },
    { code: '86', acr: 'cn', name: 'China (+86)', flag: '' },
    { code: '57', acr: 'co', name: 'Colombia (+57)', flag: '' },
    { code: '269', acr: 'km', name: 'Comoros (+269)', flag: '' },
    { code: '242', acr: 'cg', name: 'Congo (+242)', flag: '' },
    { code: '682', acr: 'ck', name: 'Cook Islands (+682)', flag: '' },
    { code: '506', acr: 'cr', name: 'Costa Rica (+506)', flag: '' },
    { code: '385', acr: 'hr', name: 'Croatia (+385)', flag: '' },
    { code: '53', acr: 'cu', name: 'Cuba (+53)', flag: '' },
    { code: '90', acr: 'cy', name: 'Cyprus - North (+90)', flag: '' },
    { code: '357', acr: 'cy', name: 'Cyprus - South (+357)', flag: '' },
    { code: '420', acr: 'cz', name: 'Czech Republic (+420)', flag: '' },
    { code: '45', acr: 'dk', name: 'Denmark (+45)', flag: '' },
    { code: '253', acr: 'dj', name: 'Djibouti (+253)', flag: '' },
    { code: '1809', acr: 'dm', name: 'Dominica (+1809)', flag: '' },
    { code: '1809', acr: 'do', name: 'Dominican Republic (+1809)', flag: '' },
    { code: '593', acr: 'ec', name: 'Ecuador (+593)', flag: '' },
    { code: '20', acr: 'eg', name: 'Egypt (+20)', flag: '' },
    { code: '503', acr: 'sv', name: 'El Salvador (+503)', flag: '' },
    { code: '240', acr: 'gq', name: 'Equatorial Guinea (+240)', flag: '' },
    { code: '291', acr: 'er', name: 'Eritrea (+291)', flag: '' },
    { code: '372', acr: 'ee', name: 'Estonia (+372)', flag: '' },
    { code: '251', acr: 'et', name: 'Ethiopia (+251)', flag: '' },
    { code: '500', acr: 'fk', name: 'Falkland Islands (+500)', flag: '' },
    { code: '298', acr: 'fo', name: 'Faroe Islands (+298)', flag: '' },
    { code: '679', acr: 'fj', name: 'Fiji (+679)', flag: '' },
    { code: '358', acr: 'fi', name: 'Finland (+358)', flag: '' },
    { code: '33', acr: 'fr', name: 'France (+33)', flag: '' },
    { code: '594', acr: 'gf', name: 'French Guiana (+594)', flag: '' },
    { code: '689', acr: 'pf', name: 'French Polynesia (+689)', flag: '' },
    { code: '241', acr: 'ga', name: 'Gabon (+241)', flag: '' },
    { code: '220', acr: 'gm', name: 'Gambia (+220)', flag: '' },
    { code: '7880', acr: 'ge', name: 'Georgia (+7880)', flag: '' },
    { code: '49', acr: 'de', name: 'Germany (+49)', flag: '' },
    { code: '233', acr: 'gh', name: 'Ghana (+233)', flag: '' },
    { code: '350', acr: 'gi', name: 'Gibraltar (+350)', flag: '' },
    { code: '30', acr: 'gr', name: 'Greece (+30)', flag: '' },
    { code: '299', acr: 'gl', name: 'Greenland (+299)', flag: '' },
    { code: '1473', acr: 'gd', name: 'Grenada (+1473)', flag: '' },
    { code: '590', acr: 'gp', name: 'Guadeloupe (+590)', flag: '' },
    { code: '671', acr: 'gu', name: 'Guam (+671)', flag: '' },
    { code: '502', acr: 'gt', name: 'Guatemala (+502)', flag: '' },
    { code: '224', acr: 'gn', name: 'Guinea (+224)', flag: '' },
    { code: '245', acr: 'gw', name: 'Guinea - Bissau (+245)', flag: '' },
    { code: '592', acr: 'gy', name: 'Guyana (+592)', flag: '' },
    { code: '509', acr: 'ht', name: 'Haiti (+509)', flag: '' },
    { code: '504', acr: 'hn', name: 'Honduras (+504)', flag: '' },
    { code: '852', acr: 'hk', name: 'Hong Kong (+852)', flag: '' },
    { code: '36', acr: 'hu', name: 'Hungary (+36)', flag: '' },
    { code: '354', acr: 'is', name: 'Iceland (+354)', flag: '' },
    { code: '91', acr: 'in', name: 'India (+91)', flag: '' },
    { code: '62', acr: 'id', name: 'Indonesia (+62)', flag: '' },
    { code: '964', acr: 'iq', name: 'Iraq (+964)', flag: '' },
    { code: '98', acr: 'ir', name: 'Iran (+98)', flag: '' },
    { code: '353', acr: 'ie', name: 'Ireland (+353)', flag: '' },
    { code: '972', acr: 'il', name: 'Israel (+972)', flag: '' },
    { code: '39', acr: 'it', name: 'Italy (+39)', flag: '' },
    { code: '1876', acr: 'jm', name: 'Jamaica (+1876)', flag: '' },
    { code: '81', acr: 'jp', name: 'Japan (+81)', flag: '' },
    { code: '962', acr: 'jo', name: 'Jordan (+962)', flag: '' },
    { code: '7', acr: 'kz', name: 'Kazakhstan (+7)', flag: '' },
    { code: '254', acr: 'ke', name: 'Kenya (+254)', flag: '' },
    { code: '686', acr: 'ki', name: 'Kiribati (+686)', flag: '' },
    { code: '850', acr: 'kp', name: 'Korea - North (+850)', flag: '' },
    { code: '82', acr: 'kr', name: 'Korea - South (+82)', flag: '' },
    { code: '965', acr: 'kw', name: 'Kuwait (+965)', flag: '' },
    { code: '996', acr: 'kg', name: 'Kyrgyzstan (+996)', flag: '' },
    { code: '856', acr: 'la', name: 'Laos (+856)', flag: '' },
    { code: '371', acr: 'lv', name: 'Latvia (+371)', flag: '' },
    { code: '961', acr: 'lb', name: 'Lebanon (+961)', flag: '' },
    { code: '266', acr: 'ls', name: 'Lesotho (+266)', flag: '' },
    { code: '231', acr: 'lr', name: 'Liberia (+231)', flag: '' },
    { code: '218', acr: 'ly', name: 'Libya (+218)', flag: '' },
    { code: '417', acr: 'li', name: 'Liechtenstein (+417)', flag: '' },
    { code: '370', acr: 'lt', name: 'Lithuania (+370)', flag: '' },
    { code: '352', acr: 'lu', name: 'Luxembourg (+352)', flag: '' },
    { code: '853', acr: 'mo', name: 'Macao (+853)', flag: '' },
    { code: '389', acr: 'mk', name: 'Macedonia (+389)', flag: '' },
    { code: '261', acr: 'mg', name: 'Madagascar (+261)', flag: '' },
    { code: '265', acr: 'mw', name: 'Malawi (+265)', flag: '' },
    { code: '60', acr: 'my', name: 'Malaysia (+60)', flag: '' },
    { code: '960', acr: 'mv', name: 'Maldives (+960)', flag: '' },
    { code: '223', acr: 'ml', name: 'Mali (+223)', flag: '' },
    { code: '356', acr: 'mt', name: 'Malta (+356)', flag: '' },
    { code: '692', acr: 'mh', name: 'Marshall Islands (+692)', flag: '' },
    { code: '596', acr: 'mq', name: 'Martinique (+596)', flag: '' },
    { code: '222', acr: 'mr', name: 'Mauritania (+222)', flag: '' },
    { code: '269', acr: 'yt', name: 'Mayotte (+269)', flag: '' },
    { code: '52', acr: 'mx', name: 'Mexico (+52)', flag: '' },
    { code: '691', acr: 'fm', name: 'Micronesia (+691)', flag: '' },
    { code: '373', acr: 'md', name: 'Moldova (+373)', flag: '' },
    { code: '377', acr: 'mc', name: 'Monaco (+377)', flag: '' },
    { code: '976', acr: 'mn', name: 'Mongolia (+976)', flag: '' },
    { code: '1664', acr: 'ms', name: 'Montserrat (+1664)', flag: '' },
    { code: '212', acr: 'ma', name: 'Morocco (+212)', flag: '' },
    { code: '258', acr: 'mz', name: 'Mozambique (+258)', flag: '' },
    { code: '95', acr: 'mn', name: 'Myanmar (+95)', flag: '' },
    { code: '264', acr: 'na', name: 'Namibia (+264)', flag: '' },
    { code: '674', acr: 'nr', name: 'Nauru (+674)', flag: '' },
    { code: '977', acr: 'np', name: 'Nepal (+977)', flag: '' },
    { code: '31', acr: 'nl', name: 'Netherlands (+31)', flag: '' },
    { code: '687', acr: 'nc', name: 'New Caledonia (+687)', flag: '' },
    { code: '505', acr: 'ni', name: 'Nicaragua (+505)', flag: '' },
    { code: '227', acr: 'ne', name: 'Niger (+227)', flag: '' },
    { code: '234', acr: 'ng', name: 'Nigeria (+234)', flag: '' },
    { code: '683', acr: 'nu', name: 'Niue (+683)', flag: '' },
    { code: '672', acr: 'nf', name: 'Norfolk Islands (+672)', flag: '' },
    { code: '670', acr: 'np', name: 'Northern Marianas (+670)', flag: '' },
    { code: '47', acr: 'no', name: 'Norway (+47)', flag: '' },
    { code: '968', acr: 'om', name: 'Oman (+968)', flag: '' },
    { code: '92', acr: 'pk', name: 'Pakistan (+92)', flag: '' },
    { code: '680', acr: 'pw', name: 'Palau (+680)', flag: '' },
    { code: '507', acr: 'pa', name: 'Panama (+507)', flag: '' },
    { code: '675', acr: 'pg', name: 'Papua New Guinea (+675)', flag: '' },
    { code: '595', acr: 'py', name: 'Paraguay (+595)', flag: '' },
    { code: '51', acr: 'pe', name: 'Peru (+51)', flag: '' },
    { code: '63', acr: 'ph', name: 'Philippines (+63)', flag: '' },
    { code: '48', acr: 'pl', name: 'Poland (+48)', flag: '' },
    { code: '351', acr: 'pt', name: 'Portugal (+351)', flag: '' },
    { code: '1787', acr: 'pr', name: 'Puerto Rico (+1787)', flag: '' },
    { code: '974', acr: 'qa', name: 'Qatar (+974)', flag: '' },
    { code: '262', acr: 're', name: 'Reunion (+262)', flag: '' },
    { code: '40', acr: 'ro', name: 'Romania (+40)', flag: '' },
    { code: '7', acr: 'ru', name: 'Russia (+7)', flag: '' },
    { code: '250', acr: 'rw', name: 'Rwanda (+250)', flag: '' },
    { code: '378', acr: 'sm', name: 'San Marino (+378)', flag: '' },
    { code: '239', acr: 'st', name: 'Sao Tome &amp; Principe (+239)', flag: '' },
    { code: '966', acr: 'sa', name: 'Saudi Arabia (+966)', flag: '' },
    { code: '221', acr: 'sn', name: 'Senegal (+221)', flag: '' },
    { code: '381', acr: 'cs', name: 'Serbia (+381)', flag: '' },
    { code: '248', acr: 'sc', name: 'Seychelles (+248)', flag: '' },
    { code: '232', acr: 'sl', name: 'Sierra Leone (+232)', flag: '' },
    { code: '65', acr: 'sg', name: 'Singapore (+65)', flag: '' },
    { code: '421', acr: 'sk', name: 'Slovak Republic (+421)', flag: '' },
    { code: '386', acr: 'si', name: 'Slovenia (+386)', flag: '' },
    { code: '677', acr: 'sb', name: 'Solomon Islands (+677)', flag: '' },
    { code: '252', acr: 'so', name: 'Somalia (+252)', flag: '' },
    { code: '27', acr: 'za', name: 'South Africa (+27)', flag: '' },
    { code: '34', acr: 'es', name: 'Spain (+34)', flag: '' },
    { code: '94', acr: 'lk', name: 'Sri Lanka (+94)', flag: '' },
    { code: '290', acr: 'sh', name: 'St. Helena (+290)', flag: '' },
    { code: '1869', acr: 'kn', name: 'St. Kitts (+1869)', flag: '' },
    { code: '1758', acr: 'sc', name: 'St. Lucia (+1758)', flag: '' },
    { code: '597', acr: 'sr', name: 'Suriname (+597)', flag: '' },
    { code: '249', acr: 'sd', name: 'Sudan (+249)', flag: '' },
    { code: '268', acr: 'sz', name: 'Swaziland (+268)', flag: '' },
    { code: '46', acr: 'se', name: 'Sweden (+46)', flag: '' },
    { code: '41', acr: 'ch', name: 'Switzerland (+41)', flag: '' },
    { code: '963', acr: 'sy', name: 'Syria (+963)', flag: '' },
    { code: '886', acr: 'tw', name: 'Taiwan (+886)', flag: '' },
    { code: '992', acr: 'tj', name: 'Tajikistan (+992)', flag: '' },
    { code: '66', acr: 'th', name: 'Thailand (+66)', flag: '' },
    { code: '228', acr: 'tg', name: 'Togo (+228)', flag: '' },
    { code: '676', acr: 'to', name: 'Tonga (+676)', flag: '' },
    { code: '1868', acr: 'tt', name: 'Trinidad &amp; Tobago (+1868)', flag: '' },
    { code: '216', acr: 'tn', name: 'Tunisia (+216)', flag: '' },
    { code: '90', acr: 'tr', name: 'Turkey (+90)', flag: '' },
    { code: '993', acr: 'tm', name: 'Turkmenistan (+993)', flag: '' },
    { code: '1649', acr: 'tc', name: 'Turks &amp; Caicos Islands (+1649)', flag: '' },
    { code: '688', acr: 'tv', name: 'Tuvalu (+688)', flag: '' },
    { code: '256', acr: 'ug', name: 'Uganda (+256)', flag: '' },
    { code: '380', acr: 'ua', name: 'Ukraine (+380)', flag: '' },
    { code: '971', acr: 'ae', name: 'United Arab Emirates (+971)', flag: '' },
    { code: '598', acr: 'uy', name: 'Uruguay (+598)', flag: '' },
    { code: '998', acr: 'uz', name: 'Uzbekistan (+998)', flag: '' },
    { code: '678', acr: 'vu', name: 'Vanuatu (+678)', flag: '' },
    { code: '379', acr: 'va', name: 'Vatican City (+379)', flag: '' },
    { code: '58', acr: 've', name: 'Venezuela (+58)', flag: '' },
    { code: '84', acr: 'vn', name: 'Vietnam (+84)', flag: '' },
    { code: '1', acr: 'vg', name: 'Virgin Islands - British (+1)', flag: '' },
    { code: '1', acr: 'vi', name: 'Virgin Islands - US (+1)', flag: '' },
    { code: '681', acr: 'wf', name: 'Wallis &amp; Futuna (+681)', flag: '' },
    { code: '969', acr: 'ye', name: 'Yemen (North)(+969)', flag: '' },
    { code: '967', acr: 'ye', name: 'Yemen (South)(+967)', flag: '' },
    { code: '260', acr: 'zm', name: 'Zambia (+260)', flag: '' },
    { code: '263', acr: 'zw', name: 'Zimbabwe (+263)', flag: '' }
  ];
}